spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  freemarker:
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

server:
  servlet:
    context-path: /sell
